services:
  - type: web
    name: litebits-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard.py
    envVars:
      - key: PROXY
        value: http://kcartik:kcartik@chill-ki-mutt.kcartik-vps.tech:22425
